trigger:
  - master
  - feat/*

variables:
  azureSubscriptionEndpoint: $(service-connection-name)
  azureContainerRegistry: $(container-registry-host)
  registryName: $(azureContainerRegistry)/$(Build.Repository.Name)
  imageTag: $(registryName):$(Build.BuildId)
  appName: $(app-name)

stages:
- stage: Tests
  displayName: 'Test (Node.js)'
  jobs:
    - job: Audit
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm audit
        displayName: Audit Dependencies

    - job: Linter
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm ci && npm run lint
        displayName: Lint Code

    - job: UnitTests
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm ci && npm run test
        displayName: Run Tests


# ----------------------------
# Docker Image: Build and Push
# ----------------------------

- stage: BuildImage
  displayName: 'Build (Docker)'
  jobs:
    - job: build_and_push_image
      steps:
      - script: |
          echo '##vso[task.setvariable variable=buildSha]'$(git rev-parse --short HEAD)''
          echo 'buildSha set to $(buildSha)'
        displayName: Get build git sha

      - script: docker build --tag $(imageTag)-$(buildSha) .
        displayName: 'Docker: Build and tag image'

      # Use the task to avoid embedding credentials in pipeline
      - task: Docker@1
        displayName: 'Docker: login ACR'
        inputs:
          command: login
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)

      - script: docker push $(imageTag)-$(buildSha)
        displayName: 'Docker: Push image'

      - script: docker logout $(azureContainerRegistry)
        displayName: 'Docker: logout ACR'

# ----------------------------
# Deploy to Azure App Services
# ----------------------------

- stage: DeployImage
  displayName: 'Deploy (master only)'
  jobs:
  - job: deploy_image
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy container as Azure Web App
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) # (master branch and succesful builds only)
      inputs:
        appName: $(appName)
        azureSubscription: $(azureSubscriptionEndpoint)
        imageName: $(imageTag)-$(buildSha)