jobs:
- job: AppService
  displayName: Deploy to App Service
  steps:

  - script: echo "##vso[task.setvariable variable=imageTag]$(npm run --silent my-version)"
    displayName: Image Tag - use app version
    condition: eq(variables.isProduction, 'True')

  - template: ../steps/append-sha.yaml

  - template: ../steps/debug-vars.yaml

  - task: AzureWebAppContainer@1
    displayName: Deploy Web App Container
    inputs:
      appName:  $(webAppName)
      azureSubscription: $(armConnection)
      imageName: $(dockerImage):$(imageTag)
